services:
  discord-bot:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - VIRTUAL_HOST=discord-bot.ryanricher.com
      - LETSENCRYPT_HOST=discord-bot.ryanricher.com
      - VIRTUAL_PORT=3000
    volumes:
      - ./cookies.txt:/app/cookies.txt
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
